name: Scrape latest data

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '7,22,37,52 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl 'https://utilisocial.io/datacapable/v1/map/events/SeattleCityLight?inProgress=true' | jq 'del(.[].createdDate) | del(.[].lastUpdated) | del(.[].polygons[].id)' > outages.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push